name: PullRequest (CI)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'
      - name: Install dependencies
        run: pnpm install
      - name: Run linter
        run: pnpm run lint
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: api_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'
      - name: Install dependencies
        run: pnpm install
      - name: Wait for Postgres
        run: sleep 10
      - name: Run tests
        run: pnpm run test
